export const Industries = [
  "Technology",
  "Healthcare",
  "Finance",
  "Marketing and Advertising",
  "Education",
  "Environmental Services",
  "Human Resources",
  "Hospitality and Tourism",
  "Real Estate",
  "Manufacturing and Engineering",
  "Entertainment",
  "Retail",
  "Telecommunications",
  "Pharmaceuticals and Biotechnology",
  "Aerospace and Aviation",
  "Automotive",
  "Legal Services",
  "Fashion and Apparel",
  "Consulting",
  "Social Work and Nonprofit",
];

export const JobType = [
  "Full Time",
  "Part Time",
  "Internship",
  "Contract",
  "Remote",
];

export const Countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor (Timor-Leste)",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast (Côte d'Ivoire)",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, North (North Korea)",
  "Korea, South (South Korea)",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar (Burma)",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia (formerly Macedonia)",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City (Holy See)",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const experienceLevels = [
  "Intern",
  "Entry-Level",
  "Junior",
  "Mid-Level",
  "Senior",
  "Lead",
  "Manager",
  "Director",
  "Vice President",
  "C-Level",
  "Executive",
];

export const jobCategories = [
  "Software Developer",
  "Data Scientist",
  "Product Manager",
  "UX/UI Designer",
  "Quality Assurance Engineer",
  "DevOps Engineer",
  "Systems Administrator",
  "Network Engineer",
  "Cybersecurity Specialist",
  "Business Analyst",
  "Project Manager",
  "Technical Support Specialist",
  "Database Administrator",
  "Cloud Architect",
  "Mobile App Developer",
  "AI/ML Engineer",
  "Full Stack Developer",
  "Frontend Developer",
  "Backend Developer",
  "IT Consultant",
  "Sales Engineer",
  "Marketing Specialist",
  "Content Writer",
  "Graphic Designer",
  "Human Resources Manager",
  "Financial Analyst",
  "Operations Manager",
  "Supply Chain Manager",
  "Customer Support Representative",
  "Legal Counsel",
  "Compliance Officer",
  "Digital Marketing Specialist",
  "SEO Specialist",
  "Social Media Manager",
  "Recruiter",
  "Training and Development Specialist",
  "Research Scientist",
  "Public Relations Specialist",
  "Art Director",
  "Copywriter",
  "Event Planner",
  "Accountant",
  "Internal Auditor",
  "Investment Analyst",
  "Healthcare Administrator",
  "Clinical Research Coordinator",
  "Pharmacist",
  "Nurse Practitioner",
  "Physician Assistant",
  "Technical Writer",
];
